<a href="https://colab.research.google.com/github/VishalPrem1994/AIGenPlayGround/blob/main/TFAutoModelForTokenClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
!pip install transformers datasets

In [ ]:
!pip install transformers -U
!pip install accelerate -U

In [87]:
from transformers import AutoProcessor, TFAutoModelForTokenClassification, Trainer
import accelerate
import transformers

In [133]:
from transformers import AutoProcessor, TFAutoModelForTokenClassification, Trainer
from datasets import load_dataset

processor = AutoProcessor.from_pretrained("microsoft/layoutlmv3-base", apply_ocr=False)
model = TFAutoModelForTokenClassification.from_pretrained("microsoft/layoutlmv3-base", num_labels=7)

dataset = load_dataset("nielsr/funsd-layoutlmv3", split="test")
example = dataset[0]
image = example["image"]
words = example["tokens"]
boxes = example["bboxes"]
word_labels = example["ner_tags"]

encoding = processor(image, words, boxes=boxes, word_labels=word_labels, return_tensors="tf")

outputs = model(**encoding)
# loss = outputs.loss
# logits = outputs.logits

All model checkpoint layers were used when initializing TFLayoutLMv3ForTokenClassification.

Some layers of TFLayoutLMv3ForTokenClassification were not initialized from the model checkpoint at microsoft/layoutlmv3-base and are newly initialized: ['dropout', 'classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [134]:
print(model.num_labels)

7


In [137]:
outputs.logits.numpy()

array([[[ 0.43296117, -0.59000134, -0.06979164, ..., -0.48452416,
          0.27750528, -0.00721444],
        [ 0.19474994, -0.25761545,  0.09597155, ...,  0.00975339,
          0.12363185,  0.01789424],
        [ 0.07014784, -0.2321267 , -0.05487693, ..., -0.18979509,
          0.06941003,  0.12577416],
        ...,
        [-0.2288545 , -0.24830306,  0.42925757, ..., -0.26319492,
         -0.24275087, -0.01112129],
        [-0.00517309, -0.4841121 ,  0.12616858, ..., -0.37430978,
          0.21132559, -0.29877675],
        [ 0.43360245, -0.5920362 , -0.06913602, ..., -0.4860724 ,
          0.27816156, -0.01015994]]], dtype=float32)

In [140]:
torch.softmax(torch.tensor(outputs.logits.numpy()),dim=-1)

tensor([[[0.2344, 0.0843, 0.1418,  ..., 0.0937, 0.2007, 0.1509],
         [0.1839, 0.1170, 0.1666,  ..., 0.1529, 0.1713, 0.1541],
         [0.1729, 0.1278, 0.1525,  ..., 0.1333, 0.1727, 0.1828],
         ...,
         [0.1288, 0.1263, 0.2487,  ..., 0.1244, 0.1270, 0.1601],
         [0.1669, 0.1034, 0.1904,  ..., 0.1154, 0.2073, 0.1245],
         [0.2347, 0.0842, 0.1420,  ..., 0.0936, 0.2009, 0.1506]]])

In [135]:
torch.convert_to_tensor(outputs.logits[0][0])

AttributeError: ignored

In [115]:
torch.tensor(outputs.logits[0])

TypeError: ignored

In [114]:
torch.Variable(outputs.logits[0])

AttributeError: ignored

In [125]:
import torch
m = torch.nn.Softmax(dim=2)
probabilities = m(outputs.logits[0])
print(probabilities)

AttributeError: ignored

In [127]:
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
output

tensor([[0.1466, 0.7651, 0.0883],
        [0.1708, 0.4912, 0.3380]])

In [112]:
input

tensor([[ 1.0653, -2.1154,  0.2749],
        [ 0.7298, -0.0619,  0.6063]])

In [86]:
accelerate.__version__

'0.23.0'

In [91]:
import accelerate
import transformers
trainer = Trainer(model=model,args=None,train_dataset=None,eval_dataset=None)

ImportError: ignored

In [61]:
outputs = model(**encoding)

In [62]:
encoding.decode(outputs)

AttributeError: ignored

In [60]:
model.predict(encoding)

ValueError: ignored

In [ ]:
example

In [ ]:
outputs

In [ ]:
model(**encoding)

In [ ]:
predictions, labels, metrics = outputs.pre(encoding)

In [37]:
from datasets import load_dataset

dataset = load_dataset("nielsr/funsd-layoutlmv3")

In [ ]:
labels = dataset['train'].features['ner_tags'].feature.names
print(labels)

In [ ]:
dataset

In [ ]:
dataset['train'][0]

In [ ]:
dataset

In [ ]:
id2label = {v: k for v, k in enumerate(labels)}
label2id = {k: v for v, k in enumerate(labels)}
label2id

In [ ]:
from PIL import Image
from datasets import Features, Sequence, ClassLabel, Value, Array2D, Array3D
# we need to define custom features
features = Features({
    'image': Array3D(dtype="int64", shape=(3, 224, 224)),
    'input_ids': Sequence(feature=Value(dtype='int64')),
    'attention_mask': Sequence(Value(dtype='int64')),
    'token_type_ids': Sequence(Value(dtype='int64')),
    'bbox': Array2D(dtype="int64", shape=(512, 4)),
    'labels': Sequence(ClassLabel(names=labels)),
})

def preprocess_data(examples):
  images = examples['image']
  words = examples['tokens']
  boxes = examples['bboxes']
  word_labels = examples['ner_tags']

  encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
                             padding="max_length", truncation=True)

  return encoded_inputs

train_dataset = dataset['train'].map(preprocess_data, batched=True, remove_columns=dataset['train'].column_names,
                                      features=features)
test_dataset = dataset['test'].map(preprocess_data, batched=True, remove_columns=dataset['test'].column_names,
                                      features=features)

In [43]:
from datasets import load_dataset

datasets = load_dataset("nielsr/funsd")

In [44]:
labels = datasets['train'].features['ner_tags'].feature.names
print(labels)

['O', 'B-HEADER', 'I-HEADER', 'B-QUESTION', 'I-QUESTION', 'B-ANSWER', 'I-ANSWER']


In [45]:
id2label = {v: k for v, k in enumerate(labels)}
label2id = {k: v for v, k in enumerate(labels)}
label2id

{'O': 0,
 'B-HEADER': 1,
 'I-HEADER': 2,
 'B-QUESTION': 3,
 'I-QUESTION': 4,
 'B-ANSWER': 5,
 'I-ANSWER': 6}

In [46]:
from PIL import Image
from transformers import LayoutLMv2Processor
from datasets import Features, Sequence, ClassLabel, Value, Array2D, Array3D

from transformers import AutoProcessor, TFAutoModelForTokenClassification
from datasets import load_dataset

processor = AutoProcessor.from_pretrained("microsoft/layoutlmv3-base", apply_ocr=False)
model = TFAutoModelForTokenClassification.from_pretrained("microsoft/layoutlmv3-base", num_labels=7)

# processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")

# we need to define custom features
features = Features({
    'image': Array3D(dtype="int64", shape=(3, 224, 224)),
    'input_ids': Sequence(feature=Value(dtype='int64')),
    'attention_mask': Sequence(Value(dtype='int64')),
    'token_type_ids': Sequence(Value(dtype='int64')),
    'bbox': Array2D(dtype="int64", shape=(512, 4)),
    'labels': Sequence(ClassLabel(names=labels)),
})

def preprocess_data(examples):
  images = [Image.open(path).convert("RGB") for path in examples['image_path']]
  words = examples['words']
  boxes = examples['bboxes']
  word_labels = examples['ner_tags']

  encoded_inputs = processor(images, words, boxes=boxes, word_labels=word_labels,
                             padding="max_length", truncation=True)

  return encoded_inputs

train_dataset = datasets['train'].map(preprocess_data, batched=True, remove_columns=datasets['train'].column_names,
                                      features=features)
test_dataset = datasets['test'].map(preprocess_data, batched=True, remove_columns=datasets['test'].column_names,
                                      features=features)

All model checkpoint layers were used when initializing TFLayoutLMv3ForTokenClassification.

Some layers of TFLayoutLMv3ForTokenClassification were not initialized from the model checkpoint at microsoft/layoutlmv3-base and are newly initialized: ['dropout', 'classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Map:   0%|          | 0/149 [00:00<?, ? examples/s]

KeyError: ignored

In [47]:
model.predict()

TypeError: ignored